server:
  port: 8000

logging:
  level:
    com.manage.metisgatewayservice: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: metis-gateway-service
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    config:
      name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus