server:
  port: 8888

spring:
  application:
    name: metis-config-service
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI}
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh ,metrics

