server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: metis-user-service
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    config:
      name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true